default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kh69784.sa-east-1.aws
      user: LHDESAFIOFINAL                          
      password: "{{ env_var('DBT_PASSWORD') }}"
      warehouse: COMPUTE_WH                 
      database: DESAFIO_FINAL            
      schema: DESAFIO_FINAL                           
      role: ACCOUNTADMIN                         
      threads: 4                                
      authenticator: snowflake                   
    

