version: 2

sources:
  - name: sap_adw
    description: Data originating from the seeds sent to Snowflake.
    database: DESAFIO_FINAL
    schema: "SAP_ADW"
    tables:
      - name: salesorderheader
        description: "This model contains sales data"
      - name: salesorderdetail
        description: "This model contains details of sales data"
      - name: salesorderheadersalesreason
        description: "This model contains sales reason data"
      - name: salesreason
        description: "This model contains sales reason data"
      - name: specialofferproduct
        description: "This model contains special offer products data"
      - name: specialoffer
        description: "This model contains special offer data"
      - name: customer
        description: "This model contains customer data."
      - name: currency
        description: "This model contains currency data."
      - name: currencyrate
        description: "This model contains currency rate data."
      - name: address
        description: "This model contains address data."
      - name: salesterritory
        description: "This model contains sales territory data."
      - name: stateprovince
        description: "This model contains territory data."
      - name: countryregion
        description: "This model contains other territory data."
      - name: salestaxrate
        description: "This model contains regional tax data."
      - name: product
        description: "This model contains product data."
      - name: productsubcategory
        description: "This model contains product subcategory data."
      - name: productcategory
        description: "This model contains product category data."
      - name: creditcard
        description: "This model contains credit card data."
      - name: personcreditcard
        description: "This model contains person credit card data."
      - name: person
        description: "This model contains persons data."
      - name: store
        description: "This model contains stores data."
      - name: salesperson
        description: "This model contains sales person data."
      - name: employee
        description: "This model contains employee data."
      - name: purchaseorderheader
        description: "This model contains purchase data"
      - name: purchaseorderdetail
        description: "This model contains purchase details."

      